export const FETCH_MATCHES_FOR_DATE = 'FETCH_MATCHES_FOR_DATE';
export const FETCH_MATCHES_FOR_DATE_SUCCESS = 'FETCH_MATCHES_FOR_DATE_SUCCESS';
export const FETCH_MATCHES_FOR_DATE_ERROR = 'FETCH_MATCHES_FOR_DATE_ERROR';

export const FETCH_MATCH_INFO = 'FETCH_MATCH_INFO';
export const FETCH_MATCH_INFO_SUCCESS = 'FETCH_MATCH_INFO_SUCCESS';
export const FETCH_MATCH_INFO_ERROR = 'FETCH_MATCH_INFO_ERROR';

export const PREVIEW_CHANGE_DATE = 'PREVIEW_CHANGE_DATE';
export const PREVIEW_SHOW_CALENDAR = 'PREVIEW_SHOW_CALENDAR';
export const PREVIEW_HIDE_CALENDAR = 'PREVIEW_HIDE_CALENDAR';
